queries = (
    'select(io, x, y, a);',
    'select(io2, x, y, a);',
    'select(iohalf, x, y, a);',
    'select(ip, x, y, a);',
    'select(it, x, y, a);',
    'select(eo, x, y, a);',
    'select(ep, x, y, a);',
    'select(vi, i, a);',
    'select(vs, i, s);',
    'subset(io, x, 2, 4);',
    'subset(io2, x, 2, 4, y, 2, 2);',
    'subset(iohalf, x, 1.2, 3.4, y, 0.732, 1.449);',
    'subset(ip, x, 1, 1, y, 2, 10);',
    'subset(it, x, 1, 2);',
    'subset(eo, x, 3, 4);',
    'subset(ep, y, 2, 6);',
    'subset(et, x, 2, 10);',
    'where(io, a >= 4 and a <= 8);',
    'where(ip, x = 2 or x = 8);',
    'where(it, not (a % 2) = 0);',
    'where(eo, x = y);',
    'where(ep, x < y);',
    'where(et, x^2 < 16);',
    'derive(io, derived, x+1);',
    'derive(ip, derived, a/1);',
    'derive(it, derived, (x+a)*2);',
    'derive(eo, derived, sqrt(x)+3);',
    'derive(ep, derived, sin(a)*cos(a));',
    'derive(et, derived, floor(x)*a);',
    'cross(io, et);',
    'cross(ip, ep);',
    'cross(it, eo);',
    'cross(eo, eo);',
    'cross(ep, it);',
    'cross(et, eo);',
    'dimjoin(io, io, x, x, y, y);',
    'dimjoin(io, io, y, y);',
    'dimjoin(io, et, x, x);',
    'dimjoin(io, io2, x, x, y, y);',
    'dimjoin(io2, iohalf, x, x, y, y);',
    'dimjoin(ip, ep, y, y);',
    'dimjoin(it, eo, x, x, y, y);',
    'dimjoin(eo, eo, x, x, y, y);',
    'dimjoin(ep, it, x, y);',
    'dimjoin(et, eo, y, x);',
    'aggregate(io, avg, a, avg_a);',
    'aggregate(iohalf, count, a, c_a, x);',
    'aggregate(ip, max, a, max_a, x);',
    'dimjoin(it, aggregate(it, min, a, min_a, y), y, y);',
    'aggregate(eo, count, x, agg, x, y);',
    'aggregate(ep, sum, y, sum_y, x);',
    'aggregate(et, avg, y, avg_y, y);',
    'select(vi);'
)
